type: 'atari'
# data_path: '/home/nas2_userI/byungkunlee/research/rl/video_rl/data/dmc'
# tmp_data_path: '/home/nas2_userI/byungkunlee/research/rl/video_rl/data/dmc'
data_path: '/data/private/video_rl/data/atari'
tmp_data_path: '/data/private/video_rl/data/atari'
game: None # defined in env config
checkpoints: [5.0, 25.0]
frames: 1 # stack num
t_step: 8 # t_step
max_size: 1000000 # 1e6
dataset_on_gpu: False #True
dataset_on_disk: True #False
batch_size: 256
full_action_set: False
num_workers: 0 # 0 means that the data will be loaded in the main process
pin_memory: True # False 
prefetch_factor: 2 # recommend to use num_workers * 2 
group_read_factor: 0 
shuffle_checkpoints: False
device: 'cuda:0'
