backbone:
    type: 'drqv2_encoder'
    obs_shape: None  # not pre-defined
    conv_filters: [32,32,32,32]
    kernel_sizes: [3,3,3,3]
    strides:      [2,1,1,1]
head: 
    type: 'None'
policy: 
    type: 'ddpg_policy'
    repr_features: None  # not pre-defined
    feat_features: 50
    hid_features: 1024
    action_shape: None  # not pre-defined
    
