project_name: 'dmc_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'ddpg'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- agent: drqv2
- env: cheetah_run
- model: ddpg