project_name: 'dmc_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'mae_vit'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- dataloader: mixed_bn256_t8
- env: cheetah_run
- trainer: mae_vit
- model: mae_vit_s
