# defaults
type: 'rainbow'
num_timesteps: 100000 # 100k
obs_shape: None
action_size: None

aug_types: [random_shift, intensity]

buffer: 
    type: 'per_buffer'
    size: 100000
    n_step: 10
    prior_exp: 0.5 # ω
    prior_weight_scheduler: # β
        initial_value: 0.4
        final_value: 1.0
        step_size: 196000  # (num_timesteps - min_buffer_size) * optimize_per_step

finetune_type: 'naive'
eval_backbone_mode: 'train'
train_backbone_mode: 'train'
train_target_backbone_mode: 'train'

optimizer:
    type: 'adam'
    lr: 0.0001
    weight_decay: 0.0
    betas: [0.9, 0.999]
    eps: 0.00015

# c51
v_min: -10
v_max: 10

# exploration
eval_eps: 0.001

# updates
double: True
gamma: 0.99
batch_size: 32
optimize_freq: 1       # loss optimization frequency 
optimize_per_step: 2   # optimization step per frequency
update_freq: 1         # target update
tau: 0.0
reset_freq: 100000000  # inf
clip_grad_norm: 10
min_buffer_size: 2000

# logging
log_every: 1000
eval_every: 100000
vis_every: 2000

# evaluation
num_eval_trajectories: 50