type: 'mae_head'
obs_shape: None
action_size: None
process_type: None
t_step: None
in_features: None
patch_size: [14, 14]
dec_depth: 2
dec_dim: 192
dec_mlp_dim: 768
dec_heads: 3
emb_dropout: 0.0
dropout: 0.0