# defaults
type: 'drqv2'
num_timesteps: None
obs_shape: None  # not-predefined
action_shape: None  # not-predefined
action_repeat: None # defined in cfg.env
game: None


# optimizer
optimizer:
    lr: 1e-4

# agent
feat_features: 50
hid_features: 1024

# update
critic_target_tau: 0.01
update_every_steps: 2
stddev_schedule: None
stddev_clip: 0.3
num_expl_steps: 2000
num_seed_steps: 2000
gamma: 0.99
batch_size: 256

# logging
log_every: 1000
eval_every: 10000

# evaluation
eval_freq: 1000
num_eval_trajectories: 10


# buffer
buffer: 
    type: 'ddpg_buffer'
    buffer_size: 1000000
    n_step: 3
    frame_stack: None
    