# dqn-nature
backbone:
    type: 'nature'
    obs_shape: None # not pre-defined
    action_size: None
    renormalize: False
    init_type: None
head:
    type: None
policy:
    type: 'rainbow'
    in_features: 3136
    hid_features: 256
    action_size: None # not pre-defined
    num_atoms: 51
    noisy_std: 0.5