# VIT-S
backbone:
    type: 'vit'
    obs_shape: None
    action_size: None
    t_step: 8
    patch_size: [14, 14]
    pool: 'cls_concat'
    enc_depth: 4
    enc_dim: 256
    enc_mlp_dim: 1024
    enc_heads: 4
    emb_dropout: 0.0
    dropout: 0.0
head:
    type: None
policy:
    type: 'rainbow'
    in_features: 2048
    hid_features: 256
    action_size: None # not pre-defined
    num_atoms: 51
    noisy_std: 0.5