# OT-Rainbow
project_name: 'atari_pretrain'
entity: 'draftrec'
exp_name: 'byol_nature'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- dataloader: mixed
- env: atari
- trainer: byol
- model: nature_byol
