project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'bcq_impala'
device: cuda:0
debug: True
seed: 0

defaults:
- _self_
- dataloader: lightweight_gpu_n640_t1
- env: atari
- trainer: bcq
- model: impala_bcq
- pretrain: scratch