# OT-Rainbow
project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'recon_impala'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- dataloader: mixed_bn256_t4
- env: atari
- trainer: recon
- model: impala_recon
