project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'dt_impala'
device: cuda:0
debug: True
seed: 0

defaults:
- _self_
- dataloader: lightweight_gpu_n64_t10
- env: atari
- trainer: dt
- model: impala_dt
- pretrain: scratch