project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'atc_impala'
device: cuda:0
debug: True
seed: 0

defaults:
- _self_
- dataloader: lightweight_gpu_n64_t13 # 13=10(t_step)+3(k_step)
- env: atari
- trainer: atc
- model: impala_atc
- pretrain: scratch
