# OT-Rainbow
project_name: 'mlr'
entity: 'draftrec'
group_name: 'mlr_training'
exp_name: 'mlr_test_lr3e-4_wd1e-2_masking50'
device: 2
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- dataloader: mixed_bn256_t4
- env: atari
- trainer: mlr
- model: impala_mlr