project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'curl_impala'
device: cuda:0
debug: True
seed: 0

defaults:
- _self_
- dataloader: lightweight
- env: atari
- trainer: curl
- model: impala_curl
- pretrain: scratch
