project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'mae_vit'
device: cuda:0
debug: True
seed: 0

defaults:
- _self_
- dataloader: lightweight
- env: atari
- trainer: mae
- model: vit_mae
- pretrain: scratch