project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'scratch_impala'
device: cuda:0
debug: True
seed: 0

defaults:
- _self_
- dataloader: lightweight_gpu
- env: atari
- trainer: scratch
- model: impala_scratch
- pretrain: scratch
