project_name: 'atari_pretrain'
entity: 'draftrec'
group_name: 'test'
exp_name: 'simclr_impala'
device: cuda:0
debug: True
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- dataloader: lightweight
- env: atari
- trainer: simclr
- model: impala_simclr
