project_name: 'simtpr_icml2023'
group_name: 'test'
exp_name: 'simtpr_pt'
device: cuda:0
debug: False
seed: 0

defaults:
- _self_
- dataloader: lightweight_gpu
- env: atari
- trainer: simtpr
- model: simtpr
- pretrain: scratch
