# dqn-nature
backbone:
    type: 'impala'
    obs_shape: None # not pre-defined
    renormalize: False
    init_type: None
head:
    type: None
policy:
    type: 'rainbow'
    in_features: 2304
    hid_features: 512
    action_size: None # not pre-defined
    num_atoms: 51
    noisy_std: 0.5