# dqn-nature
backbone:
    type: 'impala'
    obs_shape: None # not pre-defined
    renormalize: True
    init_type: None
head:
    type: byol
    in_features: 2048
    hid_features: 512
    out_features: 512
policy:
    type: None