# OT-Rainbow
project_name: 'atari100k'
exp_name: 'drq_rainbow'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- agent: rainbow
- env: atari
- model: rbw_nature