# dqn-nature
backbone:
    type: 'impala'
    obs_shape: None # not pre-defined
    action_size: None
    renormalize: True
    expansion_ratio: 2
    init_type: None
head:
    type: mlr
    patch_size: [14,14]
    action_size: None
    latent_decoder_depth: 2
    latent_decoder_heads: 8
    dropout: 0.0
    hid_features: 256
    out_features: 256
    t_step: 16
policy:
    type: None