# dqn-nature
backbone:
    type: 'impala'
    obs_shape: None # not pre-defined
    action_size: None
    renormalize: True
    expansion_ratio: 2
    init_type: None
head:
    type: 'recon'
    obs_shape: None 
    action_size: None
    enc_type: 'impala'
    hog_in_features: 3136
    hog_hid_features: 1024
    hog_out_features: 729
    dec_input_shape: (64, 7, 7)
    dec_init_type: None
    expansion_ratio: 2
policy:
    type: None