# dqn-nature
backbone:
    type: 'nature'
    obs_shape: None # not pre-defined
    renormalize: False
    init_type: None
head:
    type: curl
    in_features: 3136
    hid_features: 256
    out_features: 256
policy:
    type: None