backbone:
    type: 'nature'
    obs_shape: None
    action_size: None
    process_type: 'stack_frame'
    expansion_ratio: 1
    renormalize: True
    init_type: None
head:
    type: simclr
    in_features: 3136
    hid_features: 256
    out_features: 256
policy:
    type: None