# VIT-S
backbone:
    type: 'vit'
    obs_shape: None
    action_size: None
    t_step: None
    patch_size: [14, 14]
    pool: 'identity'
    enc_depth: 8
    enc_dim: 128
    enc_mlp_dim: 512
    enc_heads: 2
    emb_dropout: 0.0
    dropout: 0.1
    renormalize: False
head:
    type: None
policy:
    type: None