# VIT-S
backbone:
    type: 'vit'
    obs_shape: None
    action_size: None
    patch_size: [14, 14]
    time_span: None
    pool: 'mean'
    enc_depth: 4
    enc_dim: 256
    enc_mlp_dim: 1024
    enc_heads: 4
    dec_depth: 2 
    dec_dim: 128
    dec_mlp_dim: 512
    dec_heads: 2 
    emb_dropout: 0.1
    dropout: 0.1 
    init_type: None
head:
    type: None
policy:
    type: None