# VIT-S
backbone:
    type: 'vit'
    obs_shape: None
    action_size: None
    t_step: None
    patch_size: [14, 14]
    pool: 'identity'
    enc_depth: 8
    enc_dim: 128
    enc_mlp_dim: 512
    enc_heads: 2
    emb_dropout: 0.0
    dropout: 0.0
head:
    type: 'vit_head'
    obs_shape: None
    action_size: None
    t_step: None
    patch_size: [14, 14]
    enc_dim: 128    
    dec_depth: 2
    dec_dim: 128
    dec_mlp_dim: 512
    dec_heads: 2
    emb_dropout: 0.0
    dropout: 0.0
policy:
    type: None