# VIT-S
backbone:
    type: 'vit'
    obs_shape: None
    action_size: None
    t_step: None
    patch_size: [14, 14]
    pool: 'identity'
    enc_depth: 4
    enc_dim: 256
    enc_mlp_dim: 1024
    enc_heads: 4
    emb_dropout: 0.0
    dropout: 0.0
head:
    type: 'vit_head'
    obs_shape: None
    action_size: None
    t_step: None
    patch_size: [14, 14]
    enc_dim: 256
    dec_depth: 2
    dec_dim: 256
    dec_mlp_dim: 1024
    dec_heads: 4
    emb_dropout: 0.0
    dropout: 0.0
policy:
    type: None