# OT-Rainbow
project_name: 'atari_pretrain'
exp_name: 'simclr'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- dataloader: mixed
- env: atari
- trainer: simclr
- model: nature_simclr
