# OT-Rainbow
project_name: 'atari_finetune'
entity: 'draftrec'
group_name: 'test'
exp_name: 'der'
device: cuda:0
seed: 0

# pretrained-backbone
use_artifact: False
artifact_name: ''
model_path: ''

defaults:
- _self_
- agent: der
- env: atari
- model: de