backbone:
    type: 'drqv2_encoder'
    obs_shape: None  # not pre-defined
    conv_filters: [32,32,32,32]
    kernel_sizes: [3,3,3,3]
    strides:      [2,1,1,1]
    action_size: None
head:
    type: byol
    in_features: None
    hid_features: 512
    out_features: 512
policy:
    type: None