# defaults
type: 'byol'
obs_shape: None
action_size: None
t_step: None

aug_types: [random_shift, intensity]

optimizer:
    type: 'adamw'
    lr: 0.0001
    weight_decay: 0.0000001 #1e-6
    betas: [0.9, 0.999]
    eps: 0.00015

scheduler:
    cycle_mult: 1.0
    max_lr: 0.0001
    min_lr: 0.0001
    warmup_ratio: 0.2
    gamma: 1.0

# updates
batch_size: None
num_epochs: 10
clip_grad_norm: 0.5
tau: 0.99

# logging
base_metric: 'act_f1'
log_every: 1000
eval_every: 1
save_every: 5
