# defaults
type: 'clt'
obs_shape: None
action_size: None
t_step: None

aug_types: [random_shift, intensity]
mask_type: 'none'
mask_strategy: 'agnostic'
mask_ratio: 0.5
patch_size: [12, 12]

optimizer:
    type: 'adamw'
    lr: 0.0003
    weight_decay: 0.00001
    betas: [0.9, 0.999]
    eps: 0.00015

scheduler:
    cycle_mult: 1.0
    max_lr: 0.0003
    min_lr: 0.0003
    warmup_ratio: 0.2
    gamma: 1.0

tau_scheduler:
    initial_value: 0.99
    final_value: 0.999
    step_size: None
    
dataset_type: 'trajectory' # video, demonstration, trajectory
obs_lmbda: 1.0
act_lmbda: 1.0
idm_lmbda: 0.0
rew_lmbda: 1.0

obs_loss_type: consistency # consistency, contrastive
temperature: None # temperature is used when loss_type is contrastive
                  # we use consistency loss by default
    
# updates
batch_size: None
num_epochs: 10
clip_grad_norm: 0.5

# logging
base_metric: 'act_f1'
log_every: 1000
eval_every: 1
save_every: 5

# zero-shot policy evaluation
eval_policy: False
num_eval_trajectories: 50
eval_eps: 0.001

# mcts
rollout: 
    type: 'mcts'
    history_len: 10
    num_simulations: 400
    max_depth: 40
    tree_policy: 'puct'
    c_p: 5
    