# defaults
type: 'curl'
obs_shape: None
action_size: None
t_step: None

aug_types: [random_shift, intensity]

optimizer:
    type: 'adamw'
    lr: 0.0001
    weight_decay: 0.0000001 #1e-6
    betas: [0.9, 0.999]
    eps: 0.00015
    
scheduler:
    cycle_mult: 1.0
    max_lr: 0.0001
    min_lr: 0.0001
    warmup_ratio: 0.2
    gamma: 1.0
    
tau_scheduler:
    initial_value: 0.99
    final_value: 0.999
    step_size: None

# updates
batch_size: None
num_epochs: 100
clip_grad_norm: 0.5
temperature: 0.1

# logging
base_metric: 'act_f1'
log_every: 1000
eval_every: 10
save_every: 50

# zero-shot policy evaluation
eval_policy: False
num_eval_trajectories: 50
eval_eps: 0.001
