# defaults
type: 'curl'

obs_shape: None
action_size: None
t_step: None

aug_types: [random_shift, intensity]

optimizer:
    type: 'adam'
    lr: 0.0001
    weight_decay: 0.0000001 #1e-6
    betas: [0.9, 0.999]
    eps: 0.00015

# updates
num_epochs: 10
batch_size: 256
update_freq: 2
temperature: 0.1
tau: 0.99

# logging
log_every: 1000
eval_every: 10
save_every: 10
