# defaults
type: 'gpt'
obs_shape: None
action_size: None
t_step: None

aug_types: [random_shift, intensity]
mask_type: 'none'
mask_strategy: 'agnostic'
mask_ratio: 0.5
patch_size: [12, 12]

optimizer:
    type: 'adamw'
    lr: 0.0003
    weight_decay: 0.00001
    betas: [0.9, 0.999]
    eps: 0.00015

scheduler:
    cycle_mult: 1.0
    max_lr: 0.0003
    min_lr: 0.0003
    warmup_ratio: 0.2
    gamma: 1.0
    
dataset_type: 'video' # video, demonstration, trajectory
obs_lmbda: 1.0
act_lmbda: 1.0

cons_lmbda: 1.0
barlow_lmbda: 0.01
temperature: 0.1      # temperature is used when loss_type is contrastive
lmbda: 0.005          # lmbda is used when loss_type is barlow

# updates
batch_size: None
num_epochs: 10
clip_grad_norm: 0.5

# logging
base_metric: 'act_f1'
log_every: 1000
eval_every: 1
save_every: 5

# zero-shot policy evaluation
eval_policy: False
num_eval_trajectories: 50
num_envs: 1
eval_eps: 0.001

rollout: 
    type: 'beam'
    beam_width: 4
    horizon: 5
    context_len: 10
    gamma: 0.99