# defaults
type: 'mae'
loss_type: 'patch'
pretrain_type: 'naive'

obs_shape: None
action_size: None
t_step: None
patch_size: None
num_patches: None

aug_types: [random_shift, intensity] #, intensity]

# masking
patch_mask_type: 'agnostic'
patch_mask_ratio: 0.75
act_mask_ratio: 0.0

optimizer:
    type: 'adamw'
    lr: 0.003
    weight_decay: 0.001
    betas: [0.9, 0.95]
    eps: 0.00015
    
scheduler:
    cycle_mult: 1.0
    max_lr: 0.003
    min_lr: 0.0003
    warmup_steps: 10
    gamma: 1.0

# updates
num_epochs: 100
batch_size: 256
clip_grad_norm: 1.0

# logging
log_every: 100
eval_every: 2000
save_every: 50
