# defaults
type: 'mae'

obs_shape: None
action_size: None
t_step: None
num_patches: None

aug_types: []

# masking
patch_mask_type: 'agnostic'
patch_mask_ratio: 0.8
act_mask_ratio: 0.6

optimizer:
    type: 'adam'
    lr: 0.0001
    weight_decay: 0.0000001 #1e-6
    betas: [0.9, 0.999]
    eps: 0.00015

# updates
num_epochs: 10
batch_size: 64

# logging
log_every: 1000
eval_every: 10
save_every: 10
