# defaults
type: 'mae'
obs_shape: None
action_size: None
process_type: None
t_step: None
patch_size: None
num_patches: None

aug_prob: 0.5
aug_types: [random_shift, intensity]

# masking
patch_mask_type: 'agnostic'
patch_mask_ratio: 0.75

optimizer:
    type: 'adamw'
    lr: 0.003
    weight_decay: 0.001
    betas: [0.9, 0.95]
    eps: 0.00015
    
scheduler:
    cycle_mult: 1.0
    max_lr: 0.003
    min_lr: 0.0003
    warmup_ratio: 0.2
    gamma: 1.0

# updates
num_epochs: 200
batch_size: None
clip_grad_norm: 0.02

# logging
log_every: 1000
eval_every: 2000
save_every: 100
