# defaults
type: 'mlr'

obs_shape: None
action_size: None
t_step: None
patch_size: None
num_patches: None

aug_types: []

# masking
patch_mask_type: 'cube'
patch_mask_ratio: 0.5

optimizer:
    type: 'adamw'
    lr: 0.0003
    weight_decay: 0.01
    betas: [0.9, 0.95]
    eps: 0.00015
    
scheduler:
    cycle_mult: 1.0
    max_lr: 0.0003
    min_lr: 0.00003
    warmup_steps: 1
    gamma: 1.0

# updates
num_epochs: 10
batch_size: 32
clip_grad_norm: 1.0
update_freq: 1
tau: 0.99

# logging
log_every: 1000
eval_every: 10
save_every: 50
