# defaults
type: 'mlr'
obs_shape: None
action_size: None
t_step: None

aug_types: [random_shift, intensity]
mask_type: 'pixel'
mask_strategy: 'agnostic'
mask_ratio: 0.5
patch_size: [12, 12]

optimizer:
    type: 'adamw'
    lr: 0.0003
    weight_decay: 0.00001
    betas: [0.9, 0.999]
    eps: 0.00015
    
scheduler:
    cycle_mult: 1.0
    max_lr: 0.0003
    min_lr: 0.0003
    warmup_ratio: 0.2
    gamma: 1.0
    
tau_scheduler:
    initial_value: 0.99
    final_value: 0.999
    step_size: None

# updates
batch_size: None
num_epochs: 10
clip_grad_norm: 0.5
idm_lmbda: 0.0

# logging
base_metric: 'act_f1'
log_every: 1000
eval_every: 1
save_every: 5

