# defaults
type: 'recon'

obs_shape: None
action_size: None
t_step: None
patch_size: None
num_patches: None

aug_prob: 0.5
aug_types: [random_shift, intensity]

optimizer:
    type: 'adamw'
    lr: 0.003
    weight_decay: 0.001
    betas: [0.9, 0.95]
    eps: 0.00015
    
scheduler:
    cycle_mult: 1.0
    max_lr: 0.003
    min_lr: 0.0003
    warmup_steps: 20
    gamma: 1.0

# updates
num_epochs: 200
batch_size: 256
clip_grad_norm: 0.01

# logging
log_every: 200
eval_every: 1000
save_every: 100
